from typing import TypedDict, List, Dict, Any

class PlannerState(TypedDict):
    # Inputs
    student_profile: Dict[str, Any]  # name, email, preferred_study_time, etc.
    subjects: List[Dict[str, Any]]    # list of {name, difficulty, priority}
    topics: List[Dict[str, Any]]      # list of {subject_name, title, status, confidence}
    exam_date: str                    # YYYY-MM-DD
    daily_hours: float                # hours per day user has free
    
    # State generated by agent workers
    research_data: Dict[str, Any]     # search explanations, formulas, reference links indexed by topic title
    notes: Dict[str, Any]             # generated notes in Markdown indexed by topic title
    quizzes: Dict[str, Any]           # generated quizzes indexed by topic title
    quiz_scores: List[Dict[str, Any]] # history of quiz submissions: {topic_title, score, date}
    schedule: Dict[str, Any]          # optimized timetable mapping days to topics and study hours
    analysis: Dict[str, Any]          # performance report: productivity/learning score, weekly suggestion
    motivation: Dict[str, Any]        # motivational message, study tips, break tips, Pomodoro advice
