from typing import Any, TypedDict


JsonObject = dict[str, Any]
TopicRecord = dict[str, Any]

class PlannerState(TypedDict):
    # Inputs
    student_profile: JsonObject  # name, email, preferred_study_time, etc.
    subjects: list[JsonObject]  # list of {name, difficulty, priority}
    topics: list[TopicRecord]  # list of {subject_name, title, status, confidence}
    exam_date: str                    # YYYY-MM-DD
    daily_hours: float                # hours per day user has free
    
    # State generated by agent workers
    research_data: dict[str, Any]  # explanations, formulas, and links by topic title
    notes: dict[str, Any]  # generated Markdown notes by topic title
    quizzes: dict[str, Any]  # generated quizzes by topic title
    quiz_scores: list[JsonObject]  # history: {topic_title, score, date}
    schedule: dict[str, Any]  # optimized timetable mapping days to study blocks
    analysis: JsonObject  # performance report and weekly suggestion
    motivation: JsonObject  # motivational message and study advice
